services:
  - type: web
    name: adolpho-web-service
    env: node
    plan: free
    repo: https://github.com/AdolphoBorgesSalvador/Adolpho-Blueprints-Render
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adolpho-database
          property: connectionString

databases:
  - name: adolpho-database
    plan: free
    region: oregon